### ISSUE TITLE
2.1 requirements page - class def not found

### ISSUE THREAD

**Issue by veenarm** [stephanrauh/AngularFaces#70]
The url: 
https://www.angularfaces.net/version2.1/version2.1/tutorial/step_99/requirements.jsf

Is returning:
An Error Occurred:
javax/servlet/jsp/jstl/core/Config

viewId=null
phaseId=RENDER_RESPONSE(6)

Caused by:
java.lang.NoClassDefFoundError - javax/servlet/jsp/jstl/core/Config
at org.apache.myfaces.view.jsp.JspViewDeclarationLanguage.buildView(JspViewDeclarationLanguage.java:91)

java.lang.NoClassDefFoundError: javax/servlet/jsp/jstl/core/Config
    at org.apache.myfaces.view.jsp.JspViewDeclarationLanguage.buildView(JspViewDeclarationLanguage.java:91)
    at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:78)
    at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:267)
    at javax.faces.webapp.FacesServlet.service(FacesServlet.java:200)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
    at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:827)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)

<UIViewRoot class="class javax.faces.component.UIViewRoot" clientId="j_id__v_0" id="j_id__v_0" inView="true" locale="en" renderKitId="HTML_BASIC" rendered="true" transient="false"/> - State size:464 bytes

**Comment by stephanrauh** [comment]
The correct link is https://www.angularfaces.net/version2.1/tutorial/step_99/requirements.jsf. The link above has two "version2.1" instead of a single one. Is there a wrong link somewhere on my page?

**Comment by veenarm** [comment]
On page: https://www.angularfaces.net/version2.1/tutorial/step_00/index.jsf
Under Requirements
You find the requirements in a // dedicated chapter // . Cutting a long story short: You need Java 6 and JSF 2.2.

Dedicated chapter has a URL to it (it's the one that's broken).

**Comment by stephanrauh** [comment]
AngularFaces was an interesting project, but it turned out to be impossible to migrate it to Angular 2, and since the, the Java community has abandoned UI programming altogether. So I'm closing all remaining tickets and archive the project.
